version: 2

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    environment:
      MAVEN_OPTS: -Xmx1024m

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          - v1-dependencies-
      - run: |
           mvn dependency:resolve-plugins
           mvn dependency:go-offline || true
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run:
          name: Build
          command: |
            mvn package -DskipTests=true
      - store_artifacts:
          path: main/target/oce-tools.jar

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
